package Q8;

import java.util.Random;
import java.util.concurrent.*;

public class GenerateRandomNumber {

    static void main(String[] args) throws ExecutionException, InterruptedException {

        Callable<Integer> task = () -> {
            Random random = new Random();
            int num = random.nextInt(145);
            System.out.println("Generated by "+Thread.currentThread().getName());
            return num;
        };

        ExecutorService executor = Executors.newSingleThreadExecutor();

        Future<Integer> future = executor.submit(task);

        Integer result = future.get();
        System.out.println("Random integer is "+result);

        executor.shutdown();
    }
}
